"""Build SFZ instrument definitions from the downloaded sample libraries.

Outputs (all under ws5_assets/sfz/):
  <instrument>.sfz          generated SFZ for each VCSL/Iowa instrument
  mapping.json              machine-readable instrument registry used by the
                            arranger: per instrument -> sfz path, type
                            (pitched/unpitched), pitch range or articulation
                            key map, onset class label, mix gain (dB).
  samples_lnk/<Name>        space-free symlinks to the sample folders (SFZ
                            sample paths must not contain spaces).

MDL battery instruments use MDL's own (CC0) SFZ files unmodified; only their
key maps are recorded in mapping.json (keys read from the SFZ sources).

Timpani: VCSL timpani WAVs carry no pitch in the filename, so the fundamental
of each drum/tuning group is estimated with librosa.yin and the detected MIDI
key is written as pitch_keycenter (also dumped to timpani_pitches.json for
audit).
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (ASSETS, IOWA, MDL_SOUND, SFZ_DIR, VCSL_SI, VCSL_SM,
                    midi_to_note, note_to_midi)

DYN_RANK = {"pp": 0, "p": 1, "mp": 2, "mf": 3, "f": 4, "ff": 5, "fff": 6,
            "soft": 0, "med": 1, "medium": 1, "loud": 2, "hard": 2}

LNK = SFZ_DIR / "samples_lnk"


def _vel_bands(n):
    """Split 1..127 into n contiguous bands (low->high)."""
    edges = [1 + round(126 * i / n) for i in range(n)] + [127]
    return [(edges[i] + (1 if i else 0), edges[i + 1]) for i in range(n)]


def _link(folder: Path, name: str) -> Path:
    LNK.mkdir(parents=True, exist_ok=True)
    dst = LNK / name
    if not dst.is_symlink():
        dst.symlink_to(folder)
    return dst


def _region(sample, extra):
    kv = " ".join(f"{k}={v}" for k, v in extra.items())
    return f"<region> sample={sample} {kv}"


# --------------------------------------------------------------------------
# Pitched VCSL instruments: parse (note, dyn-layer, round-robin) from names.
# --------------------------------------------------------------------------
PITCHED = {
    "glockenspiel": (VCSL_SI / "Glockenspiel",
                     r"glock_(?P<dyn>soft|medium|loud)_(?P<note>[A-G]#?\d)_(?P<rr>\d+)\.wav"),
    "marimba": (VCSL_SI / "Marimba",
                r"Marimba_hit_Outrigger_(?P<note>[A-G]#?\d)_(?P<dyn>soft|med|loud)_(?P<rr>\d+)\.wav"),
    "vibraphone": (VCSL_SI / "Vibraphone",
                   r"Vibes_(?P<dyn>soft|hard)_(?P<note>[A-G]#?\d)(?:_v(?P<v>\d))?_rr(?P<rr>\d)_Main\.wav"),
    "xylophone": (VCSL_SI / "Xylophone",
                  r"Xylo_(?P<mallet>Soft|Medium|Hard)_(?P<note>[A-G]#?\d)_(?P<dyn>pp|ff)_(?P<rr>\d+)_far\.wav"),
    "chimes": (VCSL_SI / "Tubular Bells 1",
               r"chimes_(?P<note>[A-G]#?\d)_(?P<dyn>pp|p|mp|f|ff|fff)_rr(?P<rr>\d)\.wav"),
    "crotales": (IOWA / "Crotales_wav",
                 r"Crotale\.ff\.(?P<note>[A-G]b?\d)\.stereo\.wav"),
}
# xylophone: mallet+dyn combine into 6 velocity layers (soft/pp .. hard/ff)
XYLO_RANK = {("Soft", "pp"): 0, ("Soft", "ff"): 1, ("Medium", "pp"): 2,
             ("Medium", "ff"): 3, ("Hard", "pp"): 4, ("Hard", "ff"): 5}


def convert_iowa_aiffs():
    import soundfile as sf
    src = IOWA / "Crotales"
    dst = IOWA / "Crotales_wav"
    dst.mkdir(exist_ok=True)
    n = 0
    for f in sorted(src.glob("*.aif")):
        out = dst / (f.stem + ".wav")
        if not out.exists():
            data, sr = sf.read(f)
            sf.write(out, data, sr)
            n += 1
    print(f"iowa: converted {n} aiff->wav")


def build_pitched(name, folder, pat):
    lnk = _link(folder, name)
    # note -> dyn_rank -> [files]  (values are folder-relative paths)
    table = defaultdict(lambda: defaultdict(list))
    unmatched = []
    for f in sorted(folder.rglob("*.wav")):
        m = re.fullmatch(pat, f.name)
        if not m:
            unmatched.append(f.name)
            continue
        g = m.groupdict()
        if name == "xylophone":
            rank = XYLO_RANK[(g["mallet"], g["dyn"])]
        elif name == "vibraphone":
            # mallet soft/hard is the main layer; v-number sub-layers within
            rank = DYN_RANK[g["dyn"]] * 10 + int(g.get("v") or 0)
        elif "dyn" in g and g["dyn"]:
            rank = DYN_RANK[g["dyn"]]
        else:
            rank = 0
        rel = str(f.relative_to(folder)).replace("\\", "/")
        table[note_to_midi(g["note"])][rank].append(rel)
    if unmatched:
        print(f"  {name}: {len(unmatched)} unmatched files skipped: {unmatched[:4]}")

    notes = sorted(table)
    lines = [f"// generated by build_sfz.py  instrument={name}",
             "<control>", f"default_path=samples_lnk/{name}/",
             "<global> loop_mode=one_shot amp_veltrack=90"]
    for i, midi in enumerate(notes):
        lo = midi if i == 0 else (notes[i - 1] + midi) // 2 + 1
        hi = midi if i == len(notes) - 1 else (midi + notes[i + 1]) // 2
        ranks = sorted(table[midi])
        bands = _vel_bands(len(ranks))
        for (lovel, hivel), rank in zip(bands, ranks):
            files = sorted(table[midi][rank])
            for seq, fn in enumerate(files, 1):
                lines.append(_region(fn, {
                    "lokey": lo, "hikey": hi, "pitch_keycenter": midi,
                    "lovel": lovel, "hivel": hivel,
                    "seq_length": len(files), "seq_position": seq}))
    out = SFZ_DIR / f"{name}.sfz"
    out.write_text("\n".join(lines) + "\n")
    return {"sfz": out.name, "type": "pitched",
            "range": [min(notes), max(notes)],
            "sampled_notes": [midi_to_note(n) for n in notes],
            "source_folder": str(folder.relative_to(ASSETS))}


# --------------------------------------------------------------------------
# Timpani: pitch-detect each drum/tuning group, write hit + roll SFZs.
# --------------------------------------------------------------------------
def _detect_f0(path):
    import librosa
    import numpy as np
    y, sr = librosa.load(path, sr=22050, mono=True, offset=0.02, duration=1.5)
    f0 = librosa.yin(y, fmin=55, fmax=350, sr=sr, frame_length=2048)
    # keep frames with decent energy
    rms = librosa.feature.rms(y=y, frame_length=2048, hop_length=512)[0]
    n = min(len(f0), len(rms))
    f0, rms = f0[:n], rms[:n]
    good = f0[rms > 0.2 * rms.max()]
    hz = float(np.median(good if len(good) else f0))
    return hz, int(round(librosa.hz_to_midi(hz)))


def build_timpani():
    audit = {}

    def groups_of(folder, pat):
        g = defaultdict(list)
        for f in sorted(folder.glob("**/*.wav")):
            m = re.fullmatch(pat, f.name)
            if m:
                g[m.group("grp")].append((f, m.groupdict()))
        return g

    def make(name, folder, pat, gain_note):
        lnk = _link(folder, name)
        groups = groups_of(folder, pat)
        pitched = {}
        for grp, files in groups.items():
            hz, midi = _detect_f0(files[0][0])
            audit[f"{name}/{grp}"] = {"hz": round(hz, 1), "midi": midi,
                                      "note": midi_to_note(midi),
                                      "probe": files[0][0].name}
            pitched.setdefault(midi, []).extend(files)
        notes = sorted(pitched)
        lines = [f"// generated by build_sfz.py  instrument={name}",
                 f"// {gain_note}",
                 "<control>", f"default_path=samples_lnk/{name}/",
                 "<global> loop_mode=one_shot amp_veltrack=90"]
        for i, midi in enumerate(notes):
            lo = midi if i == 0 else (notes[i - 1] + midi) // 2 + 1
            hi = midi if i == len(notes) - 1 else (midi + notes[i + 1]) // 2
            byv = defaultdict(list)
            for f, g in pitched[midi]:
                byv[int(g.get("v") or 0)].append(f)
            ranks = sorted(byv)
            for (lovel, hivel), rank in zip(_vel_bands(len(ranks)), ranks):
                files = sorted(byv[rank], key=lambda p: p.name)
                for seq, f in enumerate(files, 1):
                    rel = f.relative_to(folder)
                    lines.append(_region(str(rel).replace("\\", "/"), {
                        "lokey": lo, "hikey": hi, "pitch_keycenter": midi,
                        "lovel": lovel, "hivel": hivel,
                        "seq_length": len(files), "seq_position": seq}))
        (SFZ_DIR / f"{name}.sfz").write_text("\n".join(lines) + "\n")
        return {"sfz": f"{name}.sfz", "type": "pitched",
                "range": [min(notes), max(notes)],
                "sampled_notes": [midi_to_note(n) for n in notes],
                "source_folder": str(folder.relative_to(ASSETS))}

    hit = make("timpani_hit", VCSL_SM / "Timpani 2",
               r"Timpani(?P<grp>\d[A-Z])_hit_v(?P<v>\d)_rr(?P<rr>\d)_main\.wav",
               "VCSL Timpani 2, pitch detected per drum/tuning group")
    roll = make("timpani_roll", VCSL_SM / "Timpani 1",
                r"Timpani(?P<grp>\d)_Roll_v(?P<v>\d)_rr(?P<rr>\d)_Sum\.wav",
                "VCSL Timpani 1 rolls, pitch detected per drum")
    (SFZ_DIR / "timpani_pitches.json").write_text(json.dumps(audit, indent=1))
    return hit, roll


# --------------------------------------------------------------------------
# Unpitched VCSL instruments: articulation groups -> fixed keys from 60 up.
# --------------------------------------------------------------------------
UNPITCHED = {
    "woodblock": VCSL_SI / "Woodblock",
    "cowbell": VCSL_SI / "Cowbells",
    "triangle": VCSL_SI / "Triangles",
    "tambourine": VCSL_SI / "Tambourine 1",
    "tambourine2": VCSL_SI / "Tambourine 2",
    "shaker_large": VCSL_SI / "Shaker, Large",
    "shaker_small": VCSL_SI / "Shaker, Small",
    "cabasa": VCSL_SI / "Cabasa",
}


def build_unpitched(name, folder):
    lnk = _link(folder, name)
    # articulation group = filename minus rr / dyn / v / vl tokens
    table = defaultdict(lambda: defaultdict(list))  # group -> rank -> files
    for f in sorted(folder.rglob("*.wav")):
        if "Legacy" in f.parts[len(folder.parts):-1]:
            continue
        stem = f.stem
        stem = re.sub(r"_rr\d+", "", stem)
        stem = re.sub(r"_Mid$|_far$", "", stem)
        rank = 0
        m = re.search(r"_(pp|p|mp|mf|f|ff|fff)(?=_|$)", stem)
        if m:
            rank = DYN_RANK[m.group(1)]
            stem = stem[:m.start()] + stem[m.end():]
        m = re.search(r"_(?:v|vl)(\d+)(?=_|$)", stem)
        if m:
            rank = int(m.group(1))
            stem = stem[:m.start()] + stem[m.end():]
        rel = str(f.relative_to(folder)).replace("\\", "/")
        table[stem][rank].append(rel)
    artics = {}
    lines = [f"// generated by build_sfz.py  instrument={name}",
             "<control>", f"default_path=samples_lnk/{name}/",
             "<global> loop_mode=one_shot amp_veltrack=90"]
    for i, grp in enumerate(sorted(table)):
        key = 60 + 2 * i
        artics[grp] = key
        ranks = sorted(table[grp])
        for (lovel, hivel), rank in zip(_vel_bands(len(ranks)), ranks):
            files = sorted(table[grp][rank])
            for seq, fn in enumerate(files, 1):
                lines.append(_region(fn, {
                    "key": key, "lovel": lovel, "hivel": hivel,
                    "seq_length": len(files), "seq_position": seq}))
    (SFZ_DIR / f"{name}.sfz").write_text("\n".join(lines) + "\n")
    return {"sfz": f"{name}.sfz", "type": "unpitched", "artics": artics,
            "source_folder": str(folder.relative_to(ASSETS))}


# --------------------------------------------------------------------------
# MDL battery: use MDL's own SFZ; key maps below were read from those files.
# --------------------------------------------------------------------------
def mdl_instruments():
    def rel(p):
        return str((MDL_SOUND / p).relative_to(ASSETS))
    return {
        "snareline": {
            "sfz_abs": str(MDL_SOUND / "MDL_SnareLine.sfz"), "type": "unpitched",
            "artics": {"hit": 60, "rimshot": 61, "rimknock": 62, "rim": 63,
                       "pingshot": 64, "stickshot": 65, "doubleshot": 66,
                       "backstick": 67, "crush_short": 57, "crush_long": 58,
                       "roll": 59},
            "source_folder": rel("MDL_SnareLine.sfz")},
        "tenorline": {
            "sfz_abs": str(MDL_SOUND / "MDL_TenorLine.sfz"), "type": "unpitched",
            "artics": {"hit_d4": 60, "hit_d3": 61, "hit_d2": 62, "hit_d1": 63,
                       "hit_sp2": 64, "hit_sp1": 65,
                       "rim_d4": 72, "rim_d3": 73, "rim_d2": 74, "rim_d1": 75,
                       "crush_d4": 48, "crush_d3": 49, "crush_d2": 50, "crush_d1": 51,
                       "roll_d4": 66, "roll_d3": 67, "roll_d2": 68, "roll_d1": 69},
            "source_folder": rel("MDL_TenorLine.sfz")},
        "bassline": {
            "sfz_abs": str(MDL_SOUND / "MDL_BassLine.sfz"), "type": "unpitched",
            "artics": {"unison": 60, "d6": 61, "d5": 62, "d4": 64, "d3": 66,
                       "d2": 68, "d1": 70, "rim_unison": 72,
                       "crush_unison": 48, "roll_unison": 36},
            "source_folder": rel("MDL_BassLine.sfz")},
        "cymballine": {
            "sfz_abs": str(MDL_SOUND / "MDL_CymbalLine.sfz"), "type": "unpitched",
            "artics": {"crash_fff": 60, "crash_choke": 64, "crash_mp": 67},
            "source_folder": rel("MDL_CymbalLine.sfz")},
    }


# mix gains (dB) applied at stem-mix time; class = onset label taxonomy
CLASS_GAIN = {
    "glockenspiel": ("glockenspiel", -8), "marimba": ("marimba", 0),
    "vibraphone": ("vibraphone", -1), "xylophone": ("xylophone", -3),
    "chimes": ("chimes", -3), "crotales": ("crotales", -8),
    "timpani_hit": ("timpani", 1), "timpani_roll": ("timpani", 0),
    "woodblock": ("woodblock", -5), "cowbell": ("cowbell", -6),
    "triangle": ("triangle", -9), "tambourine": ("tambourine", -5),
    "tambourine2": ("tambourine", -5), "shaker_large": ("shaker", -7),
    "shaker_small": ("shaker", -7), "cabasa": ("cabasa", -7),
    "snareline": ("snareline", -2), "tenorline": ("tenorline", -3),
    "bassline": ("bassline", -1), "cymballine": ("cymballine", -6),
}


def main():
    SFZ_DIR.mkdir(parents=True, exist_ok=True)
    convert_iowa_aiffs()
    reg = {}
    for name, (folder, pat) in PITCHED.items():
        reg[name] = build_pitched(name, folder, pat)
        print(f"built {name}: notes {reg[name]['sampled_notes']}")
    hit, roll = build_timpani()
    reg["timpani_hit"], reg["timpani_roll"] = hit, roll
    print(f"built timpani_hit: {hit['sampled_notes']}")
    print(f"built timpani_roll: {roll['sampled_notes']}")
    for name, folder in UNPITCHED.items():
        reg[name] = build_unpitched(name, folder)
        print(f"built {name}: artics {list(reg[name]['artics'])}")
    reg.update(mdl_instruments())
    for name, info in reg.items():
        cls, gain = CLASS_GAIN[name]
        info["class"] = cls
        info["gain_db"] = gain
    (SFZ_DIR / "mapping.json").write_text(json.dumps({"instruments": reg}, indent=1))
    print(f"wrote {SFZ_DIR / 'mapping.json'} with {len(reg)} instruments")


if __name__ == "__main__":
    main()
